[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "topax"
version = "0.1.0"
requires-python = ">=3.13"
urls = {homepage = "https://github.com/xwpken/topax"}
authors = [
  {name = "Weipeng Xu", email = "wxuby@connect.ust.hk"},
  {name = "Tianju Xue", email = "cetxue@ust.hk"}
]
description = "Topology optimization with differentiable finite element analysis."
dependencies = [
    "mmapy>=0.3.1",
]
readme = "README.md"
license = {file = "LICENSE"}

[tool.setuptools.packages.find]
where = ["."]
include = ["topax*"]
